Feature/add custom notification class
nextapps-be/laravel-verification-code pull request #4
Opened 2020-08-20 14:22 UTC by yinx

Add support for overriding the notification that will be used to send the verification code.

2020-08-24 07:08 UTC, earnould requested changes
Can you document the custom notification feature in the readme.md?

2020-08-25 08:09 UTC, gdebrauwer requested changes

2020-08-25 08:09 UTC, gdebrauwer commented on tests/VerificationCodeTest.php
> +            });
this does not run I think, because no notification is being sent if the notification-class is incorrect. So this code can be removed probably?

2020-08-25 08:09 UTC, gdebrauwer commented on config/verification-code.php
> +    | It should implement Illuminate\Contracts\Queue\ShouldQueue.
`and NextApps\VerificationCode\Notifications\VerificationCodeInterface`

2020-08-28 18:51 UTC, earnould commented on README.md
> +
Maybe we should opt for something like this?
```suggestion
If you want to use a custom notification to send the verification code, you can create your own notification class which should extend the `VerificationCodeInterface`. Make sure you don't forget to pass the verification code to the mail.
```

2020-08-28 18:51 UTC, earnould commented on config/verification-code.php
> +    |
Maybe we can write this out in the following way
```suggestion
    | It should implement:
    | - Illuminate\Contracts\Queue\ShouldQueue
    | - NextApps\VerificationCode\Notifications\VerificationCodeInterface
```

2020-08-28 21:27 UTC, earnould approved these changes

2020-09-01 10:56 UTC, gdebrauwer requested changes

2020-09-01 10:56 UTC, gdebrauwer commented on src/Notifications/VerificationCodeInterface.php
> +interface VerificationCodeInterface
should we not better name this `VerificationCodeCreatedInterface`, similar to the real notification class `VerificationCodeCreated`? 
`VerificationCodeInterface` seems like you can override the `VerificationCode` model class

2020-09-01 10:58 UTC, gdebrauwer commented
When we merge this and create a release, I think we should tag it as a v0.2.0

2020-09-01 12:45 UTC, gdebrauwer approved these changes

2020-09-01 12:46 UTC, merged